server:
  port: 1888
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
logging:
  level:
    "[org.springframework.web]": debug
